CREATE DATABASE PROYECTO_FINAL_BD
GO
USE PROYECTO_FINAL_BD
GO

CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT NOT NULL IDENTITY(1,1),
PRIMER_NOMBRE VARCHAR(100) NOT NULL,
SEGUNDO_NOMBRE VARCHAR(100),
TERCER_NOMBRE VARCHAR(100),
PRIMERO_APELLIDO VARCHAR(100) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(100),
APELLIDO_CASADA VARCHAR(100),
GENERO CHAR(1) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
DEPARTAMENTO VARCHAR(50),
MUNICIPIO VARCHAR(50),
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_EMPLEADO)
)
GO
CREATE TABLE USUARIO
(
ID_USUARIO INT NOT NULL IDENTITY(1,1),
ID_EMPLEADO INT NOT NULL,
LOGIN VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY (ID_USUARIO),
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
)
GO
CREATE TABLE RUTA
(
ID_RUTA INT NOT NULL IDENTITY(1,1),
DESCRIPCION VARCHAR(100) NOT NULL,
MUNICIPIO VARCHAR(50),
DEPARTAMENTO VARCHAR(50),
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_RUTA)
)
GO
CREATE TABLE EMPLEADO_RUTA
(
ID_EMPLEADO_RUTA INT NOT NULL IDENTITY(1,1),
ID_EMPLEADO INT,
ID_RUTA INT,
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_EMPLEADO_RUTA, ID_EMPLEADO, ID_RUTA),
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
FOREIGN KEY(ID_RUTA) REFERENCES RUTA(ID_RUTA)
)
GO
CREATE TABLE CLIENTE
(
ID_CLIENTE INT NOT NULL IDENTITY(1,1),
PRIMER_NOMBRE VARCHAR(100) NOT NULL,
SEGUNDO_NOMBRE VARCHAR(100),
TERCER_NOMBRE VARCHAR(100),
PRIMER_APELLIDO VARCHAR(100),
SEGUNDO_APELLIDO VARCHAR(100),
APELLIDO_CASADA VARCHAR(100),
GENERO VARCHAR(15),
DIRECCION_RESIDENCIA VARCHAR(200),
DEPARTAMENTO VARCHAR(50),
MUNICIPIO VARCHAR(50),
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_CLIENTE)
)
GO
CREATE TABLE SUCURSAL
(
ID_SUCURSAL INT NOT NULL IDENTITY(1,1),
NOMBRE_SUCURSAL VARCHAR(100),
DIRECCION_SUCURSAL VARCHAR(100),
DEPARTAMENTO VARCHAR(50),
MUNICIPIO VARCHAR(50),
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_SUCURSAL)
)
GO 
CREATE TABLE SUCURSAL_CLIENTE
(
ID_SUCURSAL_CLIENTE INT NOT NULL IDENTITY(1,1),
ID_CLIENTE INT,
ID_SUCURSAL INT,
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_SUCURSAL_CLIENTE),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
)
GO
CREATE TABLE ARTICULO
(
ID_ARTICULO INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(100) NOT NULL,
PRECIO DECIMAL(20,5) NOT NULL,
ESTADO CHAR(1),
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_ARTICULO)
)
GO
CREATE TABLE FACTURA_ENCABEZADO
(
ID_ENCABEZADO INT NOT NULL IDENTITY(1,1),
ID_CLIENTE INT,
ID_EMPLEADO INT,
FECHA_CREACION DATETIME NOT NULL,
FECHA_MODIFICACION DATETIME,
PRIMARY KEY(ID_ENCABEZADO),
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)
GO
CREATE TABLE FACTURA_DETALLE
(
ID_DETALLE INT NOT NULL IDENTITY(1,1),
ID_ENCABEZADO INT,
ID_ARTICULO INT,
PRECIO_VENTA DECIMAL(20,5),
DESCUENTO DECIMAL(5,2),
CANTIDAD DECIMAL(11,2),
PRIMARY KEY(ID_DETALLE),
FOREIGN KEY(ID_ENCABEZADO) REFERENCES FACTURA_ENCABEZADO(ID_ENCABEZADO),
FOREIGN KEY(ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO)
)
GO