USE PROYECTO_FINAL_BD
GO
CREATE PROCEDURE [dbo].[spi_FACTURA_DETALLE]
    @IDENCABEZADO AS int,
    @IDARTICULO AS int,
    @PRECIOVENTA AS decimal(20,5),
    @DESCUENTO AS decimal(5,2),
    @CANTIDAD AS decimal(11,2)

AS BEGIN

    DECLARE @FilasInsertadas TABLE (Id int)

    INSERT INTO [FACTURA_DETALLE]
    (
        [ID_ENCABEZADO],
        [ID_ARTICULO],
        [PRECIO_VENTA],
        [DESCUENTO],
        [CANTIDAD]
    )
    OUTPUT	INSERTED.ID_DETALLE
    INTO	@FilasInsertadas
    VALUES
    (
        @IDENCABEZADO,
        @IDARTICULO,
        @PRECIOVENTA,
        @DESCUENTO,
        @CANTIDAD
    )

    SELECT TOP 1
        Id
    FROM
        @FilasInsertadas


END
GO

CREATE PROCEDURE [dbo].[spu_FACTURA_DETALLE]
    @IDFACTURADETALLE AS int,
    @IDFACTURAENCABEZADO AS int,
    @IDARTICULOINVENTARIOBODEGA AS int,
    @PRECIOVENTA AS decimal(20,5),
    @DESCUENTO AS decimal(5,2),
    @CANTIDAD AS decimal(11,2)
AS BEGIN

   UPDATE
        [FACTURA_DETALLE]   SET

        [ID_ENCABEZADO] = @IDFACTURAENCABEZADO,
        [ID_ARTICULO] = @IDARTICULOINVENTARIOBODEGA,
        [PRECIO_VENTA] = @PRECIOVENTA,
        [DESCUENTO] = @DESCUENTO,
        [CANTIDAD] = @CANTIDAD
   WHERE
        [ID_DETALLE] = @IDFACTURADETALLE 

END
GO

CREATE PROCEDURE [dbo].[spd_FACTURA_DETALLE]
    @IDFACTURADETALLE AS int
AS BEGIN

    DELETE FROM
        [FACTURA_DETALLE]
    WHERE
        [ID_DETALLE] = @IDFACTURADETALLE 

END
GO

CREATE PROCEDURE [dbo].[spc_FACTURA_DETALLE]
    @IDFACTURADETALLE AS int = NULL,
    @IDFACTURAENCABEZADO AS int = NULL,
    @IDARTICULOINVENTARIOBODEGA AS int = NULL,
    @PRECIOVENTA AS decimal(20,5) = NULL,
    @DESCUENTO AS decimal(5,2) = NULL,
    @CANTIDAD AS decimal(11,2) = NULL
AS BEGIN

    SELECT
        [ID_DETALLE] ,
        [ID_ENCABEZADO] ,
        [ID_ARTICULO] ,
        [PRECIO_VENTA] ,
        [DESCUENTO] ,
        [CANTIDAD] 
    FROM
        [FACTURA_DETALLE]
    WHERE
isnull(@IDFACTURADETALLE,isnull(ID_DETALLE,0)) = isnull(ID_DETALLE,0) AND
isnull(@IDFACTURAENCABEZADO,isnull(ID_ENCABEZADO,0)) = isnull(ID_ENCABEZADO,0) AND
isnull(@IDARTICULOINVENTARIOBODEGA,isnull(ID_ARTICULO,0)) = isnull(ID_ARTICULO,0) AND
isnull(@PRECIOVENTA,isnull(PRECIO_VENTA,0)) = isnull(PRECIO_VENTA,0) AND
isnull(@DESCUENTO,isnull(DESCUENTO,0)) = isnull(DESCUENTO,0) AND
isnull(@CANTIDAD,isnull(CANTIDAD,0)) = isnull(CANTIDAD,0) 

END
GO


