USE PROYECTO_FINAL_BD
GO
CREATE PROCEDURE [dbo].[spi_FACTURA_ENCABEZADO]
    @IDCLIENTE AS int,
    @IDEMPLEADO AS int,
    @FECHACREACION AS datetime,
    @FECHAMODIFICACION AS datetime = NULL

AS BEGIN

    DECLARE @FilasInsertadas TABLE (Id int)

    INSERT INTO [FACTURA_ENCABEZADO]
    (
        [ID_CLIENTE],
        [ID_EMPLEADO],
        [FECHA_CREACION],
        [FECHA_MODIFICACION]
    )
    OUTPUT	INSERTED.ID_ENCABEZADO
    INTO	@FilasInsertadas
    VALUES
    (
        @IDCLIENTE,
        @IDEMPLEADO,
        @FECHACREACION,
        @FECHAMODIFICACION
    )

    SELECT TOP 1
        Id
    FROM
        @FilasInsertadas


END
GO
CREATE PROCEDURE [dbo].[spu_FACTURA_ENCABEZADO]
    @IDFACTURAENCABEZADO AS int,
    @IDCLIENTE AS int,
    @IDEMPLEADO AS int,
    @FECHACREACION AS datetime,
    @FECHAMODIFICACION AS datetime
AS BEGIN

   UPDATE
        [FACTURA_ENCABEZADO]   SET

        [ID_CLIENTE] = @IDCLIENTE,
        [ID_EMPLEADO] = @IDEMPLEADO,
        [FECHA_CREACION] = @FECHACREACION,
        [FECHA_MODIFICACION] = @FECHAMODIFICACION
   WHERE
        [ID_ENCABEZADO] = @IDFACTURAENCABEZADO 

END
GO

CREATE PROCEDURE [dbo].[spd_FACTURA_ENCABEZADO]
    @IDENCABEZADO AS int
AS BEGIN

    DELETE FROM
        [FACTURA_ENCABEZADO]
    WHERE
        [ID_ENCABEZADO] = @IDENCABEZADO 

END
GO

CREATE PROCEDURE [dbo].[spc_FACTURA_ENCABEZADO]
    @IDFACTURAENCABEZADO AS int = NULL,
    @IDCLIENTE AS int = NULL,
    @IDEMPLEADO AS int = NULL,
    @FECHACREACION AS datetime = NULL,
    @FECHAMODIFICACION AS datetime = NULL
AS BEGIN

    SELECT
        [ID_ENCABEZADO] ,
        [ID_CLIENTE] ,
        [ID_EMPLEADO] ,
        [FECHA_CREACION] ,
        [FECHA_MODIFICACION] 
    FROM
        [FACTURA_ENCABEZADO]
    WHERE
isnull(@IDFACTURAENCABEZADO,isnull(ID_ENCABEZADO,0)) = isnull(ID_ENCABEZADO,0) AND
isnull(@IDCLIENTE,isnull(ID_CLIENTE,0)) = isnull(ID_CLIENTE,0) AND
isnull(@IDEMPLEADO,isnull(ID_EMPLEADO,0)) = isnull(ID_EMPLEADO,0) AND
isnull(@FECHACREACION,isnull(FECHA_CREACION,getdate())) = isnull(FECHA_CREACION,getdate()) AND
isnull(@FECHAMODIFICACION,isnull(FECHA_MODIFICACION,getdate())) = isnull(FECHA_MODIFICACION,getdate()) 

END
GO


